services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=meow_user
      - POSTGRES_PASSWORD=meow_password
      - POSTGRES_DB=meow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meow-net

  backend:
    build: 
      context: ./backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://meow_user:meow_password@db:5432/meow_db
      - SECRET_KEY=CHANGE_THIS_IN_PRODUCTION_ENV
    networks:
      - meow-net
    depends_on:
      - db
    # No ports exposed here, frontend nginx proxies to it internally on 'backend:8080'

  frontend:
    build:
      context: ./frontend
    ports:
      - "8090:80"
    networks:
      - meow-net
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  meow-net:
    driver: bridge
